# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21e69a74835a88ddeb965b65e7c42793ae44ebeab5c99d9b02f55cc97a170a2f1008338955946c713434beac34585544043474361199fb2bcbfca82cef1889cf
  REDISTOGO_URL: redis://127.0.0.1:6379/0

  #mapbox api keys
  default_public_token: pk.eyJ1IjoibWFya21hcmttYXJrIiwiYSI6IjBVV1oxYUkifQ.eq_QpInsA8ggRqbXrJRtAw

  default_secret_token: sk.eyJ1IjoibWFya21hcmttYXJrIiwiYSI6IkJmdFFEaWcifQ.KJ7QtjxktAGA6vS0pZPqTw

  #twitter api keys
  consumer_key: fF184UJXCoOhMOSIgzurlypX0
  consumer_secret: Lq9ibiuXHz2eajFKUMCUM45wgYhNmgFqDjTzbAdGpUezy7FmQC

  #twitter api tokens
  Access_Token:  52792309-oLwLTkrX0dnClRlGio6UZgxmyao9Mg5Eb315EYsZb
Access_Token_Secret: nCCyHbcSbwAIh9AXrulo9Xt2DL074KXSQwkYKvVGbOOjL
Access_Level:  Read and write
Owner: MarkLDaniels
Owner_ID: 52792309


test:
  secret_key_base: 690f637bfcad684844a15c4e900f717bf7f07d129458a8c384ac434e9785cbb99819637e9e86c063e9d820f4f7b398fe98d3ed398de734b82d5323c03075c6b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
